config/routes.rb
Rails.application.routes.draw do

  resources :jobs, :only => [:show, :new, :create]
  patch '/jobs/:id', to: 'jobs#show'
  resources :categories, :only => [:show, :index]
  root 'categories#index'
  get 'search', to: 'search#search'
  get 'jobs' => 'categories#jobs'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
require 'elasticsearch/model'
class Job < ActiveRecord::Base
  attr_writer :current_step

  belongs_to :category
  validates :category, presence: true
  validates :job_title, :description, :headquarters, :apply, :name, :email, presence: true
  has_attached_file :logo, styles: { medium: "300x300>"}
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  def current_step
    @current_step || steps.first
  end

  def steps
    %w[form preview confirmation]
  end

  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end

  def first_step?
    current_step == steps.first
  end

  def last_step?
    current_step == steps.last
  end

  def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end
end
# Delete the previous articles index in Elasticsearch
Job.__elasticsearch__.client.indices.delete index: Job.index_name rescue nil

# Create the new index with the new mapping
Job.__elasticsearch__.client.indices.create \
  index: Job.index_name,
  body: { settings: Job.settings.to_hash, mappings: Job.mappings.to_hash }

Job.import # for auto sync model with elastic search

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  def show
    @category = Category.find(params[:id])
  end
  def jobs
    @categories = Category.all
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end
  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs=Job.all.job('created_at DESC')
  end

  def new
    session[:job_params] ||= {}
    @job = Job.new(session[:job_params])
    @job.current_step = session[:job_step]
  end

  def create
    session[:job_params].deep_merge!(params[:job]) if params[:job]
    @job = Job.new(session[:job_params])
    @job.current_step = session[:job_step]
    if @job.valid?
      if params[:back_button]
        @job.previous_step
      elsif @job.last_step?
        @job.save if @job.all_valid?
      else
        @job.next_step
      end
      session[:job_step] = @job.current_step
    end
    if @job.new_record?
      render "new"
    else
      session[:job_step] = session[:job_params] = nil
      flash[:notice] = "job saved!"
      redirect_to @job
    end
  end


  def preview
    @job = Job.find(params[:id])
  end


  def show
    @job = Job.find(params[:id])
  end

  private
    def job_params
      params.require(:job).permit(:job_title, :headquarters, :description, :apply, :name, :url, :email, :highlight,:category_id, :logo)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @jobs = []
    else
      @jobs = Job.search params[:q]
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/categories/index.html.erb
<div class="row" id="intro">
  <a href="/#intro"><strong>We Work Remotely</strong></a> is the best place to find and list jobs that aren’t
    restricted by commutes or a particular geographic area. Find the most qualified people in the most unexpected
    places: Hire remote! Follow us on Twitter
  <a class="twitter" href="https://twitter.com/dinarcse">@dinarcse</a>
</div>
<div class="row">
  <nav>
    <div class="add-listing">
      <%= link_to "Post a job: $200 for 30 days", new_job_path %>
    </div>

    <%= render 'search/form' %>
  </nav>
</div>
<div class="row jobs">
  <% for category in @categories %>
    <% if(category.jobs.count > 0) %>
      <h2><%= link_to category.name, category %><span> Latest post <%= time_ago_in_words(category.jobs.last.created_at) %> Ago</span></h2>
      <ul>
        <% for job in category.jobs %>
          <% if job.highlight == true %>
            <li class="featured">
          <% else %>
            <li>
          <% end %>
          <% if job.created_at > 1.day.ago %>
            <span class="new">New</span>
          <% end %>
            <%= link_to job do %>
              <span class="company"><%= job.name %></span>
              <span class="title"><%= job.job_title %></span>
              <span class="date"><%= job.created_at.strftime("%B %d") %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% content_for :head do %>
  <title><%= @category.name %> Jobs</title>
<% end %>

<div class="row" id="intro">
  <a href="/#intro"><strong>We Work Remotely</strong></a> is the best place to find and list jobs that aren’t
    restricted by commutes or a particular geographic area. Find the most qualified people in the most unexpected
    places: Hire remote! Follow us on Twitter
  <a class="twitter" href="https://twitter.com/dinarcse">@dinarcse</a>
</div>
<div class="row">
  <nav>
    <div class="add-listing">
      <%= link_to "Post a job: $200 for 30 days", new_job_path %>
    </div>
    <%= render 'search/form' %>
  </nav>
</div>

<div class="row jobs">
  <h2><%= @category.name %> Jobs<span> Latest post 1 day ago</span></h2>
  <ul>
    <% Job.where(category_id: @category.id).each do |job| %>
      <li>
        <a href="/jobs/<%= job.id %>">
          <span class="company"><%= job.name %></span>
          <span class="title"><%= job.job_title %></span>
          <span class="date"><%= job.created_at.strftime("%B %d") %></span>
        </a>
      </li>

    <% end %>
    <li><a class="view-all" href="/">← Back to all jobs</a></li>
  </ul>
</div>

app/views/jobs/_confirmation_step.html.erb
<h1>thanks for confirmation</h1>

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <% if @job.errors.any? %>
  		<div id="errors">
  			<h2><%= pluralize(@job.errors.count, "error") %> prevented this post from saving:</h2>
  			<ul>
  				<% @job.errors.full_messages.each do |msg| %>
  					<li><%= msg %></li>
  				<% end %>
  			</ul>
  		</div>
  	<% end %>
  <h2 class="dnew">First, tell us about the position</h2>
  <%= f.input :job_title %>
  <%= f.hint '“Senior Designer” or “Rails Programmer”' %>
  <div class="category">
  <%= f.label :Select_Category %>
  <%= f.collection_radio_buttons :category_id, Category.all, :id, :name, :item_wrapper_tag => :li, :collection_wrapper_tag => :ul %>
  </div>
  <%= f.input :headquarters %>
  <%= f.hint '“Chicago, IL”, “Stockholm, Sweden” ' %>
  <%= f.label :Job_description %>
  <%= f.trix_editor :description %><br>
  <%= f.input :apply, label: 'How do people apply for this job?', hint: 'Example: Send a resume to jane@company.com' %>
  <h2 class="dnew">Tell us about your company</h2>
  <%= f.input :name, hint: 'Enter your company or organization’s name. ' %>
  <%= f.input :logo, as: :file, hint: "Optional — Your company logo will appear at the top of your listing.
190px wide is optimal. We'll resize automatically if it's wider than 190px" %>
  <%= f.input :url, hint: 'Example: https://mybusiness.com/careers/apply' %>
  <%= f.input :email, hint: 'This is where we’ll send your receipt and confirmation email.', placeholder: 'user@domain.com' %>
  <h2 class="dnew">Help your ad stand out</h2>
  <p class="highlight">For only <strong>$50 more</strong> you can highlight your ad. Highlighted ads have a yellow background in the list so they stand out against the others.</p>
  <%= f.input :highlight, inline_label: 'Yes, highlight my ad for only $50.', as: :boolean, checked_value: true, unchecked_value: false %>
  <%= f.button :submit %>
<% end %>
<br><br><br><br>

app/views/jobs/_form_step.html.erb
  <h1 id="step">Step 1: Create your ad</h1>
  <h2 class="dnew">First, tell us about the position</h2>
  <%= f.input :job_title %>
  <%= f.hint '“Senior Designer” or “Rails Programmer”' %>
  <div class="category">
  <%= f.label :Select_Category %>
  <%= f.collection_radio_buttons :category_id, Category.all, :id, :name, :item_wrapper_tag => :li, :collection_wrapper_tag => :ul %>
  </div>
  <%= f.input :headquarters %>
  <%= f.hint '“Chicago, IL”, “Stockholm, Sweden” ' %>
  <%= f.label :Job_description %>
  <%= f.trix_editor :description %><br>
  <%= f.input :apply, label: 'How do people apply for this job?', hint: 'Example: Send a resume to jane@company.com' %>
  <h2 class="dnew">Tell us about your company</h2>
  <%= f.input :name, hint: 'Enter your company or organization’s name. ' %>
  <%= f.input :logo, as: :file, hint: "Optional — Your company logo will appear at the top of your listing.
190px wide is optimal. We'll resize automatically if it's wider than 190px" %>
  <%= f.input :url, hint: 'Example: https://mybusiness.com/careers/apply' %>
  <%= f.input :email, hint: 'This is where we’ll send your receipt and confirmation email.', placeholder: 'user@domain.com' %>
  <h2 class="dnew">Help your ad stand out</h2>
  <p class="highlight">For only <strong>$50 more</strong> you can highlight your ad. Highlighted ads have a yellow background in the list so they stand out against the others.</p>
  <%= f.input :highlight, inline_label: 'Yes, highlight my ad for only $50.', as: :boolean, checked_value: true, unchecked_value: false %>

app/views/jobs/_preview_step.html.erb
<% content_for :head do %>
  <title>Preview Job</title>
<% end %>

<div class="row show">
  <h1 id="step">Step 2: Preview your ad</h1>
</div>
<div class="row heading">
  <div class="col-md-9">
    <h1><%=h @job.job_title %></h1>

    <h2>
      <span class="company"><%=h @job.name %></span>
      <br>
      <span class="location">Headquarters: <%=h @job.headquarters %></span>
      <br>
      <%=h link_to @job.url, @job.url %>
    </h2>
  </div>
  <div class="col-md-3">
    <%=h image_tag @job.logo.url(:medium) %>
  </div>

</div>
<div class="row description">
  <div class="col-md-9 nopadding">
    <%=h @job.description.html_safe %>
  </div>
  <div class="col-md-3">
    share button will be here
  </div>
</div>
<div class="row apply">
  <h3>Apply for this position</h3>
  <p><%=h auto_link(@job.apply, :html => { :target => '_blank' }) %></p>
</div>

app/views/jobs/index.html.erb
<div class="row" id="intro">
  <a href="/#intro"><strong>We Work Remotely</strong></a> is the best place to find and list jobs that aren’t
    restricted by commutes or a particular geographic area. Find the most qualified people in the most unexpected
    places: Hire remote! Follow us on Twitter
  <a class="twitter" href="https://twitter.com/dinarcse">@dinarcse</a>
</div>
<div class="row">
  <nav>
    <div class="add-listing">
      <%= link_to "Post a job: $200 for 30 days", new_job_path %>
    </div>
    <%= render 'search/form' %>
  </nav>
</div>
<div class="row jobs">
  <h2>All Jobs<span> Latest post 1 day ago</span></h2>
  <ul>
    <% @jobs.each do |job| %>
      <li>
        <a href="/jobs/<%= job.id %>">
          <span class="company"><%= job.name %></span>
          <span class="title"><%= job.job_title %></span>
          <span class="date"><%= job.created_at.strftime("%B %d") %></span>
        </a>
      </li>
    <% end %>
  </ul>

</div>

app/views/jobs/new.html.erb
<% content_for :head do %>
  <title>Create a New Jobs</title>
<% end %>

<div class="promo">
  <p>Your job listing will remain on this site for 30 days. After 30 days your job listing will expire and be removed. You can always post the job again for $200 for another 30 days.</p>
</div>


<%= simple_form_for @job do |f| %>
<% if @job.errors.any? %>
   <div id="errors">
     <h2><%= pluralize(@job.errors.count, "error") %> prevented this Job from saving:</h2>
     <ul>
       <% @job.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
 <%= render "#{@job.current_step}_step", :f => f %>
 <p><%= f.submit 'Looks great! Continue',  class: "btn btn-danger btn-lg" %></p>
 <p><%= f.submit "Back to Previous Step", class: "btn btn-defualt btn-lg", :name => "back_button" unless @job.first_step? %></p>
<% end %>
<br><br><br><br>

app/views/jobs/show.html.erb
<% content_for :head do %>
  <title><%= @job.job_title %></title>
<% end %>

<div class="row show">
  <div class="col-md-6 text-left">
    <%= link_to "← Back to all jobs", root_path %>
  </div>
  <div class="col-md-6 text-right">
    <%= link_to "See more #{Category.find(@job.category_id).name} jobs →", category_path(@job.category_id) %>

  </div>
</div>
<div class="row heading">
  <div class="col-md-9">
    <h1><%= @job.job_title %></h1>
    <h3>Posted <%= @job.created_at.strftime("%B %d") %></h3>
    <h2>
      <span class="company"><%= @job.name %></span>
      <br>
      <span class="location">Headquarters: <%= @job.headquarters %></span>
      <br>
      <%= link_to @job.url, @job.url %>
    </h2>
  </div>
  <div class="col-md-3">
    <%= image_tag @job.logo.url(:medium) %>
  </div>

</div>
<div class="row description">
  <div class="col-md-9 nopadding">
    <%= @job.description.html_safe %>
  </div>
  <div class="col-md-3">
    share button will be here
  </div>
</div>
<div class="row apply">
  <h3>Apply for this position</h3>
  <p><%= auto_link(@job.apply, :html => { :target => '_blank' }) %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for?(:head) %>
      <%= content_for(:head) %>
    <% else %>
      <title>We Work Remotly</title>
    <% end %>
    <%= auto_discovery_link_tag :rss, jobs_url(:format => :rss) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <% if(!current_page?(root_path)) %>
      <div class="container">
        <div class="row header">
          <%= link_to root_path do %>
				      <%= image_tag "logo.jpg" %>
			    <% end %>
        </div>
      </div>
      <% end %>
      <% if(current_page?(root_path)) %>
      <div class="container">
        <div class="row header-main">
          <%= link_to root_path do %>
				      <%= image_tag "logo.jpg" %>
			    <% end %>
        </div>
      </div>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <% if(current_page?(root_path)) %>
    <div class="container-fluid footer">
      <div class="container">

      </div>
    </div>
    <% end %>
  </body>
</html>

app/views/search/_form.html.erb
<%= form_for :q, url: search_path,:html => { :id => "search_form" }, method: :get do |form| %>
  <%= text_field_tag :q, params[:q], placeholder: "Search: ‘css’, ‘javascript’, ‘rails’…" %>
<% end %>

app/views/search/search.html.erb
<% content_for :head do %>
  <title>Search Result</title>
<% end %>

<div class="row">
  <nav>
    <div class="add-listing">
      <%= link_to "Post a job: $200 for 30 days", new_job_path %>
    </div>
    <%= render 'search/form' %>
  </nav>
</div>

<div class="row jobs">

      <ul>
        <% @jobs.each do |job| %>
          <li>
            <%= link_to controller: "jobs", action: "show", id: job._id do %>
              <span class="company"><%= job.name %></span>
              <span class="title"><%= job.job_title %></span>
              <span class="date"><%= job.url %></span>
            <% end %>
          </li>
        <% end %>
      </ul>

</div>